apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai-gateway
data:
  config.yaml: |
    model_list:

      - model_name: customer-assistant
        litellm_params:
          model: openai/gpt-4o
          api_key: os.environ/OPENAI_API_KEY

      - model_name: nova-model
        litellm_params:
          model: bedrock/amazon.nova-micro-v1:0

      - model_name: claude-model
        litellm_params:
          model: bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0

    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY